### ISSUE TITLE
Use of confusing #

### ISSUE THREAD

**Issue by wmcnamara** [bravikov/nameof#3]
Hi!

I am trying to understand how this works, and I noticed this line:
`#define nameof(x) bravikov::_nameof<0>(#x, sizeof(x))`

What does the "#x" do? I've never seen something like this before, so its pretty confusing to me. Thanks!

**Comment by bravikov** [comment]
It's [the stringizing operator](https://docs.microsoft.com/en-us/cpp/preprocessor/stringizing-operator-hash?view=msvc-160).
